// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reputation_struct.proto

package proto_entity_reputation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Reputation struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UpVote               int64    `protobuf:"varint,3,opt,name=up_vote,json=upVote,proto3" json:"up_vote,omitempty"`
	DownVote             int64    `protobuf:"varint,4,opt,name=down_vote,json=downVote,proto3" json:"down_vote,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reputation) Reset()         { *m = Reputation{} }
func (m *Reputation) String() string { return proto.CompactTextString(m) }
func (*Reputation) ProtoMessage()    {}
func (*Reputation) Descriptor() ([]byte, []int) {
	return fileDescriptor_baaec7fa5f8f1f3a, []int{0}
}

func (m *Reputation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reputation.Unmarshal(m, b)
}
func (m *Reputation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reputation.Marshal(b, m, deterministic)
}
func (m *Reputation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reputation.Merge(m, src)
}
func (m *Reputation) XXX_Size() int {
	return xxx_messageInfo_Reputation.Size(m)
}
func (m *Reputation) XXX_DiscardUnknown() {
	xxx_messageInfo_Reputation.DiscardUnknown(m)
}

var xxx_messageInfo_Reputation proto.InternalMessageInfo

func (m *Reputation) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Reputation) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Reputation) GetUpVote() int64 {
	if m != nil {
		return m.UpVote
	}
	return 0
}

func (m *Reputation) GetDownVote() int64 {
	if m != nil {
		return m.DownVote
	}
	return 0
}

func (m *Reputation) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Reputation) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type ReputationVote struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Value                int64    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReputationVote) Reset()         { *m = ReputationVote{} }
func (m *ReputationVote) String() string { return proto.CompactTextString(m) }
func (*ReputationVote) ProtoMessage()    {}
func (*ReputationVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_baaec7fa5f8f1f3a, []int{1}
}

func (m *ReputationVote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReputationVote.Unmarshal(m, b)
}
func (m *ReputationVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReputationVote.Marshal(b, m, deterministic)
}
func (m *ReputationVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReputationVote.Merge(m, src)
}
func (m *ReputationVote) XXX_Size() int {
	return xxx_messageInfo_ReputationVote.Size(m)
}
func (m *ReputationVote) XXX_DiscardUnknown() {
	xxx_messageInfo_ReputationVote.DiscardUnknown(m)
}

var xxx_messageInfo_ReputationVote proto.InternalMessageInfo

func (m *ReputationVote) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ReputationVote) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ReputationVote) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Reputation)(nil), "entity.reputation.Reputation")
	proto.RegisterType((*ReputationVote)(nil), "entity.reputation.ReputationVote")
}

func init() { proto.RegisterFile("reputation_struct.proto", fileDescriptor_baaec7fa5f8f1f3a) }

var fileDescriptor_baaec7fa5f8f1f3a = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd0, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x06, 0x60, 0xea, 0xba, 0x75, 0x9b, 0x83, 0x60, 0x11, 0xb6, 0x20, 0xc2, 0xb2, 0xa7, 0xbd,
	0xb4, 0x3d, 0xf8, 0x04, 0xeb, 0x49, 0x3d, 0x78, 0xe8, 0xc1, 0x83, 0x08, 0x25, 0x9b, 0x0e, 0x6d,
	0xa0, 0xc9, 0x84, 0x74, 0x52, 0xf1, 0xc5, 0x7c, 0x3e, 0x49, 0xda, 0xb5, 0xf7, 0xbd, 0x65, 0xfe,
	0x8f, 0x09, 0xc3, 0xcf, 0xb6, 0x16, 0x8c, 0x23, 0x4e, 0x12, 0x75, 0x3d, 0x90, 0x75, 0x82, 0x0a,
	0x63, 0x91, 0x30, 0xbd, 0x03, 0x4d, 0x92, 0x7e, 0x8a, 0xc5, 0xf7, 0xbf, 0x11, 0x63, 0xd5, 0xff,
	0x98, 0x6e, 0xd9, 0x8d, 0x1b, 0xc0, 0xd6, 0xb2, 0xc9, 0xa2, 0x5d, 0x74, 0x48, 0xaa, 0xd8, 0x8f,
	0xaf, 0x4d, 0xfa, 0xc0, 0x92, 0x00, 0x9a, 0x2b, 0xc8, 0xae, 0x02, 0x6d, 0x7c, 0xf0, 0xce, 0x15,
	0x84, 0x2d, 0x53, 0x8f, 0x48, 0x90, 0xad, 0x76, 0xd1, 0x61, 0x55, 0xc5, 0xce, 0x7c, 0x20, 0x81,
	0xdf, 0x6a, 0xf0, 0x5b, 0x4f, 0x74, 0x1d, 0x68, 0xe3, 0x83, 0x80, 0x8f, 0x8c, 0x09, 0x0b, 0x9c,
	0xa0, 0xa9, 0x39, 0x65, 0xeb, 0xa0, 0xc9, 0x9c, 0x1c, 0xc9, 0xb3, 0x33, 0xcd, 0x99, 0xe3, 0x89,
	0xe7, 0xe4, 0x48, 0xfb, 0x2f, 0x76, 0xbb, 0xdc, 0x1d, 0xfe, 0xbb, 0xec, 0xf6, 0x7b, 0xb6, 0x1e,
	0x79, 0xef, 0xce, 0x97, 0x4f, 0xc3, 0xf3, 0xdb, 0xe7, 0x4b, 0x2b, 0xa9, 0x73, 0xa7, 0x42, 0xa0,
	0x2a, 0x95, 0xd4, 0xad, 0xe8, 0x50, 0x96, 0x1d, 0xf4, 0x3d, 0xe6, 0x4a, 0x0a, 0x8b, 0xf9, 0x00,
	0x76, 0x94, 0x02, 0xca, 0x50, 0x6d, 0xde, 0xe2, 0xfc, 0x98, 0x2a, 0xce, 0x97, 0x8a, 0x4f, 0x71,
	0x80, 0xa7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xed, 0xf0, 0x46, 0x97, 0x01, 0x00, 0x00,
}
