apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: service-api-reputation
  name: service-api-reputation
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: service-api-reputation
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: service-api-reputation
    spec:
      containers:
      - image: mingchoi/service-api-reputation
        name: service-api-reputation
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
